# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc41defa5d749f0df3843c257a88ee308e26682a863d729f5d41687a047b2840f2af841f364972c41fc0cf2a97b15b0d743084b7c4d16c304995820a5560d0a3

test:
  secret_key_base: e7e01efd4188221a2397f1e7f66bdd45400e550cdd37338245e5d7a0f765b757b9a65f68361c5119f5b2118ccfc61e9107915b226e19dee37994c59bfe369c2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
